### ISSUE TITLE
Names surrounded by angle brackets cause conversion to fail

### ISSUE THREAD

**Issue by ghost** [nsapa/pgo2mbox#2]
The name and email address in the pg4 file in question both look something like `<redacted@yahoogroups.com>`.

```python-traceback
Traceback (most recent call last):
  File "/usr/lib/python3.7/email/_header_value_parser.py", line 1949, in get_address
    token, value = get_group(value)
  File "/usr/lib/python3.7/email/_header_value_parser.py", line 1908, in get_group
    "display name but found '{}'".format(value))
email.errors.HeaderParseError: expected ':' at end of group display name but found ''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/email/_header_value_parser.py", line 1775, in get_mailbox
    token, value = get_name_addr(value)
  File "/usr/lib/python3.7/email/_header_value_parser.py", line 1756, in get_name_addr
    "expected name-addr but found '{}'".format(token))
email.errors.HeaderParseError: expected name-addr but found '<redacted@yahoogroups.com> <redacted@yahoogr_ oups.com>'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "pgo2mbox.py", line 405, in <module>
    if (convertpgo()):
  File "pgo2mbox.py", line 254, in convertpgo
    if (group2mbox(group, persons)):
  File "pgo2mbox.py", line 145, in group2mbox
    mail['From'] = return_yfrom(persons[ymessage[5]][0], yfrom)
  File "/usr/lib/python3.7/email/message.py", line 409, in __setitem__
    self._headers.append(self.policy.header_store_parse(name, val))
  File "/usr/lib/python3.7/email/policy.py", line 148, in header_store_parse
    return (name, self.header_factory(name, value))
  File "/usr/lib/python3.7/email/headerregistry.py", line 589, in __call__
    return self[name](name, value)
  File "/usr/lib/python3.7/email/headerregistry.py", line 197, in __new__
    cls.parse(value, kwds)
  File "/usr/lib/python3.7/email/headerregistry.py", line 340, in parse
    kwds['parse_tree'] = address_list = cls.value_parser(value)
  File "/usr/lib/python3.7/email/headerregistry.py", line 331, in value_parser
    address_list, value = parser.get_address_list(value)
  File "/usr/lib/python3.7/email/_header_value_parser.py", line 1972, in get_address_list
    token, value = get_address(value)
  File "/usr/lib/python3.7/email/_header_value_parser.py", line 1952, in get_address
    token, value = get_mailbox(value)
  File "/usr/lib/python3.7/email/_header_value_parser.py", line 1778, in get_mailbox
    token, value = get_addr_spec(value)
  File "/usr/lib/python3.7/email/_header_value_parser.py", line 1624, in get_addr_spec
    token, value = get_local_part(value)
  File "/usr/lib/python3.7/email/_header_value_parser.py", line 1452, in get_local_part
    obs_local_part, value = get_obs_local_part(str(local_part) + value)
  File "/usr/lib/python3.7/email/_header_value_parser.py", line 1500, in get_obs_local_part
    if (obs_local_part[0].token_type == 'dot' or
IndexError: list index out of range
```

**Comment by nsapa** [comment]
Hello,

Could you send me the pg4 file?
I can keep it private and not add it to the sample folder if you want.

Best regards,
NS

**Comment by ghost** [comment]
Unfortunately it's not something that I'm allowed to share. You should be able to reproduce the bug by putting angle brackets around one of the names in the person table in another pg4 file. On my end, taking them out did allow for successful conversion.

**Comment by nsapa** [comment]
Could you retry with version 0.5.1?
It should fix the issue one way or another (keeping the name or fail-safing to only the email address).

**Comment by ghost** [comment]
Seems to work now, thank you.

**Comment by nsapa** [comment]
Thanks you for creating an issue and enjoy your mbox.
